export const metadata = {
    title: "登入",
    description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
    return (
        <>
        {children}
        </>
    )
}