export const metadata = {
    title: "註冊",
    description: "Generated by create next app",
};

export default function CartLayout({ children }) {
    return (
        <>
        {children}
        </>
    )
}