import "../styles/members.scss"

export const metadata = {
  title: "會員中心",
  description: "Generated by create next app",
};

export default function CartLayout({ children }) {
  return (
    <div className="layout">
          {children}
        
    </div>
  );
}