export const metadata = {
    title: "會員中心",
    description: "Generated by create next app",
};

export default function CollectLayout({ children }) {
    return (
        <div className="layout">
            {children}            
        </div>
    );
}