export const metadata = {
    title: "發文",
    description: "Generated by create next app",
};

export default function PostLayout({ children }) {
    return (
        <>
        {children}
        </>
    )
}